### ISSUE TITLE
Error while dialing on gost v3.

### ISSUE THREAD

**Issue by fernvenue** [go-gost/plugin#1]
Hi, I just build a resolver plugin to handle DNS64 requests, but gost seems doesn't wanna use it even when I use totally the same configuration with [http-plugin](https://gost.run/en/concepts/resolver/#http-plugin):

```
services:
- name: auto
  addr: :1080
  resolver: dns64
  handler:
    type: auto
  listener:
    type: tcp
resolvers:
- name: dns64
  plugin:
    type: http
    addr: http://[::1]:5053/000
```

And here's the error message:

```
{"kind":"resolver","level":"error","msg":"rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial tcp: address http://[::1]:5053/000: too many colons in address\"","resolver":"dns64","time":"2023-10-09T22:33:23.584+06:00"}
{"handler":"auto","kind":"handler","level":"error","listener":"tcp","msg":"rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial tcp: address http://[::1]:5053/000: too many colons in address\"","service":"auto","time":"2023-10-09T22:33:23.584+06:00"}
{"handler":"auto","kind":"handler","level":"error","listener":"tcp","msg":"resolver: domain example.com does not exist","service":"auto","time":"2023-10-09T22:33:23.584+06:00"}
```

I also tried to use `127.0.0.1` instead of `::1`, same, and my plugin doesn't get any request at all :(

Any help much appreciated.
